spring.application.name=clinic

#datasource configuration
spring.datasource.url=${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/cms}
spring.datasource.username=${PGUSER:postgres}
spring.datasource.password=${PGPASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# MongoDB Configuration
spring.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/cms}

spring.web.resources.static-locations=classpath:/static/
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

api.path=/api/
jwt.secret=${JWT_SECRET}

server.forward-headers-strategy=native